//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flight_Radar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pointsloc
    {
        public int Id { get; set; }
        public Nullable<double> PointX { get; set; }
        public Nullable<double> PointY { get; set; }
    }
}
